# Generated by Django 5.2.5 on 2025-08-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar_profile_user_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
